services:
  - type: web
    name: random-walker-web
    runtime: ruby
    plan: free
    region: oregon
    autoDeployTrigger: commit
    healthCheckPath: /up
    buildCommand: ./bin/render-build
    startCommand: ./bin/render-start
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "2"
      - key: RANDOM_WALKER_INITIAL_URL
        value: https://qiita.com/
      - key: RANDOM_WALKER_ALLOWED_HOSTS
        value: qiita.com
      - key: RANDOM_WALKER_CONTACT_EMAIL
        sync: false
